import React, { useState, useEffect } from 'react';
import { 
  FileText, 
  Table as TableIcon, 
  Presentation as PresentationIcon, 
  Download, 
  Trash2, 
  Plus, 
  RefreshCw, 
  ShieldCheck, 
  FileCheck,
  CheckCircle2,
  AlertCircle
} from 'lucide-react';
import type { GeneratedFileInfo, GenerateDocumentRequest } from '../types';
import { fetchGeneratedFiles, createGeneratedDocument, deleteGeneratedFile } from '../api/client';

const GeneratedFiles: React.FC = () => {
  const [files, setFiles] = useState<GeneratedFileInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [message, setMessage] = useState<{ text: string; type: 'success' | 'error' } | null>(null);

  // Form state
  const [format, setFormat] = useState<'docx' | 'xlsx' | 'pptx'>('docx');
  const [title, setTitle] = useState('');
  const [subtitle, setSubtitle] = useState('');
  const [summary, setSummary] = useState('');
  const [useDataset, setUseDataset] = useState(true);

  const loadFiles = async () => {
    try {
      setLoading(true);
      const data = await fetchGeneratedFiles();
      setFiles(data);
    } catch (e) {
      console.error('Failed to fetch generated files:', e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadFiles();
  }, []);

  const handleGenerate = async (presetFormat?: 'docx' | 'xlsx' | 'pptx', presetTitle?: string) => {
    try {
      setGenerating(true);
      setMessage(null);

      const targetFormat = presetFormat || format;
      const targetTitle = presetTitle || title || (
        targetFormat === 'docx' 
          ? 'Equipment Maintenance & Downtime Audit Report' 
          : targetFormat === 'xlsx' 
          ? 'Plant Equipment Downtime Dataset & KPIs' 
          : 'Industrial Operational Readiness Briefing'
      );

      const req: GenerateDocumentRequest = {
        format: targetFormat,
        title: targetTitle,
        subtitle: subtitle || 'Sovereign Air-Gapped Analysis',
        summary: summary || 'Automated analytical summary generated by Sovereign AI Workbench from on-premise records.',
        use_sample_dataset: useDataset
      };

      const res = await createGeneratedDocument(req);
      setMessage({ text: res.message || `Successfully generated ${targetFormat.toUpperCase()}!`, type: 'success' });
      setTitle('');
      setSubtitle('');
      setSummary('');
      await loadFiles();
    } catch (e: any) {
      setMessage({ text: e.response?.data?.detail || 'Failed to generate document', type: 'error' });
    } finally {
      setGenerating(false);
    }
  };

  const handleDelete = async (filename: string) => {
    if (!window.confirm(`Delete ${filename}?`)) return;
    try {
      await deleteGeneratedFile(filename);
      await loadFiles();
    } catch (e) {
      console.error('Failed to delete file:', e);
    }
  };

  const getFormatIcon = (fmt: string) => {
    switch (fmt.toLowerCase()) {
      case 'docx':
        return <FileText className="w-5 h-5 text-blue-400" />;
      case 'xlsx':
        return <TableIcon className="w-5 h-5 text-emerald-400" />;
      case 'pptx':
        return <PresentationIcon className="w-5 h-5 text-amber-400" />;
      default:
        return <FileCheck className="w-5 h-5 text-slate-400" />;
    }
  };

  const docxCount = files.filter(f => f.format === 'docx').length;
  const xlsxCount = files.filter(f => f.format === 'xlsx').length;
  const pptxCount = files.filter(f => f.format === 'pptx').length;

  return (
    <div className="space-y-6 max-w-7xl mx-auto pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-bold tracking-tight text-white">Generated Files & Reports</h1>
            <span className="text-xs px-2.5 py-0.5 rounded-full bg-purple-950 text-purple-400 border border-purple-800/60 font-mono font-semibold">
              PHASE 7 ENGINE
            </span>
          </div>
          <p className="text-slate-400 text-sm mt-1">
            Automated local generation of executive Word reports, analytical Excel sheets, and PowerPoint briefings.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs px-2.5 py-1 rounded bg-emerald-950/80 text-emerald-400 border border-emerald-800/60 font-mono flex items-center gap-1.5">
            <ShieldCheck className="w-3.5 h-3.5" /> 100% AIR-GAPPED CREATION
          </span>
          <button
            onClick={loadFiles}
            disabled={loading}
            className="p-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg border border-slate-700 transition-colors"
            title="Refresh list"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <div className="p-4 bg-slate-900/60 border border-slate-800 rounded-xl">
          <div className="text-xs font-mono text-slate-500 uppercase tracking-wider">Total Documents</div>
          <div className="text-2xl font-bold font-mono text-white mt-1">{files.length}</div>
        </div>
        <div className="p-4 bg-slate-900/60 border border-blue-900/40 rounded-xl">
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono text-blue-400 uppercase tracking-wider">Word Reports (.docx)</span>
            <FileText className="w-4 h-4 text-blue-400" />
          </div>
          <div className="text-2xl font-bold font-mono text-white mt-1">{docxCount}</div>
        </div>
        <div className="p-4 bg-slate-900/60 border border-emerald-900/40 rounded-xl">
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono text-emerald-400 uppercase tracking-wider">Spreadsheets (.xlsx)</span>
            <TableIcon className="w-4 h-4 text-emerald-400" />
          </div>
          <div className="text-2xl font-bold font-mono text-white mt-1">{xlsxCount}</div>
        </div>
        <div className="p-4 bg-slate-900/60 border border-amber-900/40 rounded-xl">
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono text-amber-400 uppercase tracking-wider">Briefing Decks (.pptx)</span>
            <PresentationIcon className="w-4 h-4 text-amber-400" />
          </div>
          <div className="text-2xl font-bold font-mono text-white mt-1">{pptxCount}</div>
        </div>
      </div>

      {/* Alert message if any */}
      {message && (
        <div className={`p-4 rounded-xl border flex items-center gap-3 ${
          message.type === 'success' 
            ? 'bg-emerald-950/40 border-emerald-800/60 text-emerald-300' 
            : 'bg-red-950/40 border-red-800/60 text-red-300'
        }`}>
          {message.type === 'success' ? <CheckCircle2 className="w-5 h-5 shrink-0" /> : <AlertCircle className="w-5 h-5 shrink-0" />}
          <span className="text-sm font-medium">{message.text}</span>
        </div>
      )}

      {/* Generator Studio */}
      <div className="p-5 bg-slate-900 border border-slate-800 rounded-xl shadow-md space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800/80 pb-3">
          <div>
            <h2 className="text-base font-semibold text-white">Document Creation Studio</h2>
            <p className="text-xs text-slate-400 mt-0.5">Quickly synthesize audit deliverables from on-premise dataset</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => handleGenerate('docx', 'Equipment Maintenance & Downtime Audit Report')}
              disabled={generating}
              className="px-3 py-1.5 bg-blue-950/70 hover:bg-blue-900 text-blue-300 border border-blue-800/50 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5"
            >
              <Plus className="w-3.5 h-3.5" /> + Quick DOCX Report
            </button>
            <button
              onClick={() => handleGenerate('xlsx', 'Plant Equipment Downtime Dataset & KPIs')}
              disabled={generating}
              className="px-3 py-1.5 bg-emerald-950/70 hover:bg-emerald-900 text-emerald-300 border border-emerald-800/50 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5"
            >
              <Plus className="w-3.5 h-3.5" /> + Quick XLSX Sheet
            </button>
            <button
              onClick={() => handleGenerate('pptx', 'Industrial Operational Readiness Briefing')}
              disabled={generating}
              className="px-3 py-1.5 bg-amber-950/70 hover:bg-amber-900 text-amber-300 border border-amber-800/50 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5"
            >
              <Plus className="w-3.5 h-3.5" /> + Quick PPTX Deck
            </button>
          </div>
        </div>

        {/* Custom Form */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2">
          <div>
            <label className="block text-xs font-mono text-slate-400 mb-1">Output Format</label>
            <select
              value={format}
              onChange={(e) => setFormat(e.target.value as any)}
              className="w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-sm text-slate-200 focus:outline-none focus:border-amber-500 font-mono"
            >
              <option value="docx">Microsoft Word (.docx)</option>
              <option value="xlsx">Microsoft Excel (.xlsx)</option>
              <option value="pptx">PowerPoint Presentation (.pptx)</option>
            </select>
          </div>
          <div className="sm:col-span-2">
            <label className="block text-xs font-mono text-slate-400 mb-1">Document Title</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Critical Equipment Failure Investigation"
              className="w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-sm text-slate-200 focus:outline-none focus:border-amber-500"
            />
          </div>
        </div>

        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-2">
          <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
            <input
              type="checkbox"
              checked={useDataset}
              onChange={(e) => setUseDataset(e.target.checked)}
              className="rounded bg-slate-950 border-slate-700 text-amber-500 focus:ring-0 w-4 h-4"
            />
            <span>Auto-populate from local dataset (<span className="font-mono text-amber-400">equipment_downtime.csv</span>)</span>
          </label>

          <button
            onClick={() => handleGenerate()}
            disabled={generating}
            className="px-5 py-2 bg-amber-600 hover:bg-amber-500 text-white rounded-lg text-sm font-semibold transition-colors flex items-center justify-center gap-2 shadow disabled:opacity-50"
          >
            <Plus className="w-4 h-4" />
            {generating ? 'Generating Document...' : 'Generate Document'}
          </button>
        </div>
      </div>

      {/* File Explorer Table */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-xl overflow-hidden shadow-lg">
        <div className="px-5 py-3.5 border-b border-slate-800 bg-slate-900 flex items-center justify-between">
          <span className="text-sm font-semibold text-slate-200 uppercase tracking-wider font-mono">
            Generated Document Archive
          </span>
          <span className="text-xs text-slate-500 font-mono">
            {files.length} file{files.length === 1 ? '' : 's'} stored locally
          </span>
        </div>

        {loading ? (
          <div className="p-8 text-center text-slate-500 font-mono text-sm">Loading document repository...</div>
        ) : files.length === 0 ? (
          <div className="p-12 text-center text-slate-500 space-y-2">
            <FileCheck className="w-10 h-10 mx-auto text-slate-600" />
            <p className="text-sm font-medium text-slate-400">No generated documents yet.</p>
            <p className="text-xs text-slate-600">Use the Quick Generator buttons above to create your first report.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-800 text-[11px] font-mono text-slate-400 uppercase tracking-wider bg-slate-950/40">
                  <th className="py-3 px-4">Document</th>
                  <th className="py-3 px-4">Format</th>
                  <th className="py-3 px-4">Size</th>
                  <th className="py-3 px-4">Generated At</th>
                  <th className="py-3 px-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 text-sm">
                {files.map((file) => (
                  <tr key={file.filename} className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-3 px-4">
                      <div className="flex items-center gap-3">
                        {getFormatIcon(file.format)}
                        <span className="font-medium text-slate-200 font-mono text-xs truncate max-w-md">
                          {file.filename}
                        </span>
                      </div>
                    </td>
                    <td className="py-3 px-4">
                      <span className={`text-[11px] font-mono uppercase px-2 py-0.5 rounded border ${
                        file.format === 'docx' 
                          ? 'bg-blue-950 text-blue-400 border-blue-800/60' 
                          : file.format === 'xlsx'
                          ? 'bg-emerald-950 text-emerald-400 border-emerald-800/60'
                          : file.format === 'pptx'
                          ? 'bg-amber-950 text-amber-400 border-amber-800/60'
                          : 'bg-slate-800 text-slate-400 border-slate-700'
                      }`}>
                        {file.format}
                      </span>
                    </td>
                    <td className="py-3 px-4 font-mono text-xs text-slate-400">
                      {file.size_formatted}
                    </td>
                    <td className="py-3 px-4 font-mono text-xs text-slate-400">
                      {new Date(file.created_at).toLocaleString()}
                    </td>
                    <td className="py-3 px-4 text-right">
                      <div className="flex items-center justify-end gap-2">
                        <a
                          href={file.download_url}
                          download={file.filename}
                          className="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-amber-400 border border-slate-700 transition-colors inline-flex items-center gap-1 text-xs"
                          title="Download Document"
                        >
                          <Download className="w-3.5 h-3.5" />
                          <span className="hidden sm:inline">Download</span>
                        </a>
                        <button
                          onClick={() => handleDelete(file.filename)}
                          className="p-1.5 rounded-lg bg-slate-800 hover:bg-red-950/60 text-slate-400 hover:text-red-400 border border-slate-700 transition-colors"
                          title="Delete File"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default GeneratedFiles;
